### ISSUE TITLE
Improve UI for 'See Fingerprints' Page

### ISSUE THREAD

**Issue by stellargo** [jenkinsci/ui-ux-hackfest-2020#104]
Summary: Embed 'more details' from 4th column inside the 1st column to improve UI.

## Links 

* https://github.com/jenkinsci/jenkins/pull/4749
* https://issues.jenkins-ci.org/browse/JENKINS-62470

## Screenshots

Before:
<img width="1128" alt="Screen Shot 2020-05-27 at 1 50 51 PM" src="https://user-images.githubusercontent.com/27735438/82995354-1da5ee00-a021-11ea-8ff7-fde849699843.png">

After:
<img width="786" alt="Screen Shot 2020-05-27 at 1 46 33 PM" src="https://user-images.githubusercontent.com/27735438/82995260-00711f80-a021-11ea-99f2-c91d7246814b.png">

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @stellargo  for code
