### ISSUE TITLE
Remove subversion from suggested plugins

### ISSUE THREAD

**Issue by amuniz** [jenkinsci/ui-ux-hackfest-2020#106]
subversion plugin is not actively maintained, however it is in the list
of suggested plugins during first install. Having a unmaintained plugin
in the suggested list of plugins does not look correct.

## Links 

* https://github.com/jenkinsci/jenkins/pull/4750
* https://issues.jenkins-ci.org/browse/JENKINS-62477

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @amuniz for code
