### ISSUE TITLE
UI testing: system read permission

### ISSUE THREAD

**Issue by ksenia-nenasheva** [jenkinsci/ui-ux-hackfest-2020#109]
Summary: Tested Read-only Jenkins Configuration in UI.

ReadOnly user can modify their user profile, but this feature should be unavailable in UI.

## Links 

* https://issues.jenkins-ci.org/browse/JENKINS-62482

## Screenshots

<img width="1355" alt="Screenshot 2020-05-27 at 14 56 31" src="https://user-images.githubusercontent.com/5075432/83023363-18e73700-a02d-11ea-84ea-615e81e42414.png">

**Comment by timja** [comment]
Hi @ksenia-nenasheva 

Thanks for the testing, I've followed up with my feedback in the Jira issue

@allcontributors please add @ksenia-nenasheva for testing
