### ISSUE TITLE
JENKINS-62285 Don't use browser alert for notifications and confirmation

### ISSUE THREAD

**Issue by aytuncbeken** [jenkinsci/ui-ux-hackfest-2020#111]
Summary: Please describe what you have done here

## Links 

* Issue -> https://issues.jenkins-ci.org/browse/JENKINS-62285
* PR -> https://github.com/jenkinsci/folder-auth-plugin/pull/60

## Screenshots

![Screenshot from 2020-05-27 13-48-09](https://user-images.githubusercontent.com/17325506/83028934-5c906f80-a032-11ea-971d-8fc5bc78f570.png)
![Screenshot from 2020-05-27 13-48-21](https://user-images.githubusercontent.com/17325506/83028936-5d290600-a032-11ea-98a7-a638c37857af.png)

**Comment by timja** [comment]
please add links to the contribution, and ideally screenshots

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!
