### ISSUE TITLE
Migrating 'Pipeline CPS Method Mismatches' wiki page to jenkins.io

### ISSUE THREAD

**Issue by dwnusbaum** [jenkinsci/ui-ux-hackfest-2020#115]
I am migrating https://wiki.jenkins.io/display/JENKINS/Pipeline+CPS+method+mismatches to jenkins.io.

## Links 

* https://wiki.jenkins.io/display/JENKINS/Pipeline+CPS+method+mismatches 
* https://github.com/jenkins-infra/jenkins.io/pull/3366
* https://github.com/jenkins-infra/jenkins-infra/pull/1494.

## Screenshots

N/A

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @dwnusbaum  for docs
