### ISSUE TITLE
Improve documentation pertaining to serializability best practices in pipelines

### ISSUE THREAD

**Issue by steven-terrana** [jenkinsci/ui-ux-hackfest-2020#120]
Improves upon the existing documentation pertaining to serializability in jenkins pipelines and how to avoid the dreaded `NotSerializableException`

## Links 

* https://github.com/jenkins-infra/jenkins.io/pull/3374
* Documentation Page: https://www.jenkins.io/doc/book/pipeline/pipeline-best-practices/

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @steven-terrana  for docs

**Comment by oleg-nenashev** [comment]
Thanks!
