### ISSUE TITLE
Introduced Jenkins Hackfest #JenkinsIsTheWay

### ISSUE THREAD

**Issue by bigdevlarry** [jenkinsci/ui-ux-hackfest-2020#121]
##  Description
I talked about the Jenkins hackfest and how awesome it's been so far . I also had shared a link to the hackfest for interested participants 

## Links 

* Link 1
https://twitter.com/devlarri/status/1265567000761446404?s=20

* Link 2

https://www.linkedin.com/posts/suleolanrewaju_jenkinsciui-ux-hackfest-2020-activity-6671535719888019456-x-hj

## Screenshots
![Screenshot_20200527-202244](https://user-images.githubusercontent.com/29729601/83063331-dbe46a00-a057-11ea-8d0b-620660117ed9.png)

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @LarrySul  for content
