### ISSUE TITLE
Added source maps for CSS and JS

### ISSUE THREAD

**Issue by 95jonpet** [jenkinsci/ui-ux-hackfest-2020#123]
Added source maps for CSS and JS processed by Webpack in order to make it easier to debug machine-handled code.

## Links 

* https://github.com/jenkinsci/jenkins/pull/4753

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! It will help with the UI themes stories a lot

**Comment by oleg-nenashev** [comment]
@all-contributors please add @95jonpet  for tools
