### ISSUE TITLE
Fixing Jenkins Hackfest Acknoledgements

### ISSUE THREAD

**Issue by vsilverman** [jenkinsci/ui-ux-hackfest-2020#125]
Summary: Please describe what you have done here
Fixed "Advocacy and Outreach" endpoint in Jenkins Hackfest
## Links 

* [PR 3373](https://github.com/jenkins-infra/jenkins.io/pull/3373)
* [Jenkins Hackfest](https://www.jenkins.io/blog/2020/05/12/uiux-hackfest-announcement/#acknowledgements)

## Screenshots

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

**Comment by oleg-nenashev** [comment]
Thanks for catching the issue and for the pull request! Fixed it in an alternative pull request 

@all-contributors please add @vsilverman  for testing
