### ISSUE TITLE
Migrate Parallels Desktop Plugin to Documentation-as-Code

### ISSUE THREAD

**Issue by madsjakobsen** [jenkinsci/ui-ux-hackfest-2020#126]
Added PM to migrate docs from wiki to GitHub

 - Updated pom.xml
 - Added badges for plugin version and install count
 - Minor formatting, and text edit 

## Links 

 - https://github.com/jenkinsci/parallels-desktop-plugin/pull/6

**Comment by timja** [comment]
Thanks!

@allcontributors please add @MadsJakobsen for documentation
