### ISSUE TITLE
Convert 'Serialization of anonymous classes' wiki page to jenkins.io

### ISSUE THREAD

**Issue by v1v** [jenkinsci/ui-ux-hackfest-2020#128]
Migrate [Serialization of anonymous classes](https://wiki.jenkins.io/display/JENKINS//Serialization+of+anonymous+classes)

## Links
- https://github.com/jenkins-infra/jenkins.io/issues/3214
- jenkins-infra/jenkins.io#3378
- jenkins-infra/jenkins-infra#1495

## Screenshots

See the above-mentioned PRs.

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! Let's keep reviewing it in the pull requests
