### ISSUE TITLE
Migrate "Change Time Zone" from wiki

### ISSUE THREAD

**Issue by Taeloz** [jenkinsci/ui-ux-hackfest-2020#129]
Migrating the "Change Time Zone" page from the wiki to jenkins.io.

## Links 

* https://github.com/jenkins-infra/jenkins.io/pull/3379

**Comment by timja** [comment]
@allcontributors please add @Taeloz for documentation

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!
