### ISSUE TITLE
Script security enhancement

### ISSUE THREAD

**Issue by Wadeck** [jenkinsci/ui-ux-hackfest-2020#133]
Summary: Adding metadata gathering for Script Security approval page + capability to revoke individual approval.

## Links 

* https://github.com/jenkinsci/script-security-plugin/pull/300

## Screenshots

![image](https://user-images.githubusercontent.com/3000480/83128929-5d7ddb80-a0dc-11ea-804e-a72de0a7c347.png)

![image](https://user-images.githubusercontent.com/3000480/83128944-6373bc80-a0dc-11ea-9e0d-34d1b5603358.png)

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

**Comment by Wadeck** [comment]
<details>

<summary>Screenshots</summary>

![script-security-approval](https://user-images.githubusercontent.com/2662497/83123694-85b60c00-a0d5-11ea-872f-a027206a7365.png)

![script-security-approved](https://user-images.githubusercontent.com/2662497/83123696-86e73900-a0d5-11ea-8707-da0fd3ca7f53.png)


</details>

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!
