### ISSUE TITLE
Migrated Documentation from wiki to jenkins.io

### ISSUE THREAD

**Issue by urwa** [jenkinsci/ui-ux-hackfest-2020#135]
Summary: Migrated the following wiki page to jenkins.io "Agents with Windows Scheduler"

## Links 

* ISSUE: https://github.com/jenkins-infra/jenkins.io/issues/3319
* PULL REQUEST: https://github.com/jenkins-infra/jenkins.io/pull/3381

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! The pull request needs patches, but we can proceed there

@all-contributors please add @urwa for docs
