### ISSUE TITLE
Migrated wiki & placed redirects

### ISSUE THREAD

**Issue by krharsh17** [jenkinsci/ui-ux-hackfest-2020#137]
Summary: Migrated documentation from wiki to jenkins.io Also, placed redirects in jenkins-infra

## Links 

https://github.com/jenkins-infra/jenkins.io/pull/3383
https://github.com/jenkins-infra/jenkins.io/pull/3350
https://github.com/jenkins-infra/jenkins-infra/pull/1497
https://github.com/jenkins-infra/jenkins-infra/pull/1496

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @krharsh17 for docs

**Comment by oleg-nenashev** [comment]
Let's proceed in the pull requests
