### ISSUE TITLE
New UI for Folder Auth plugin

### ISSUE THREAD

**Issue by AbhyudayaSharma** [jenkinsci/ui-ux-hackfest-2020#142]
A new React-based UI for the [folder auth](https://plugins.jenkins.io/folder-auth) plugin.

## Links 

* https://github.com/jenkinsci/folder-auth-plugin/pull/58

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @sladyn98 for code

**Comment by oleg-nenashev** [comment]
Of, sorry 🤦 . Sladyn posted a blog anyway, so I will keep that

**Comment by oleg-nenashev** [comment]
@all-contributors please add @AbhyudayaSharma for code
