### ISSUE TITLE
Fixed up link to pipeline as yaml project

### ISSUE THREAD

**Issue by kennyg** [jenkinsci/ui-ux-hackfest-2020#145]
Summary: Small PR to update link to the pipeline as yaml project

## Links 

* https://github.com/jenkins-infra/jenkins.io/pull/3347

## Screenshots

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @kennyg for docs
