### ISSUE TITLE
Migrating Offline+Jenkins+Installation

### ISSUE THREAD

**Issue by rathneesh** [jenkinsci/ui-ux-hackfest-2020#147]
Summary: Migrate [Offline+Jenkins+Installation](https://wiki.jenkins.io/display/JENKINS/Offline+Jenkins+Installation) to [https://www.jenkins.io/doc/book/installing/](https://www.jenkins.io/doc/book/installing/)

## Links 

 [Pull request](https://github.com/jenkins-infra/jenkins.io/pull/3380)

* Link 1

## Screenshots

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @rathneesh for docs
