### ISSUE TITLE
timja bulk list of contributions

### ISSUE THREAD

**Issue by timja** [jenkinsci/ui-ux-hackfest-2020#152]
Summary: See links

## Links 

Allow anyone to view 'Manage Jenkins' - allows moving the 'Manage credentials link from the side bar to Manage Jenkins and also adds a link to 'Manage agents and nodes'
https://github.com/jenkinsci/jenkins/pull/4738
https://github.com/jenkinsci/credentials-plugin/pull/150

Moves 'Folder Authorization Strategy' from 'Uncategorized' to 'Security
https://github.com/jenkinsci/folder-auth-plugin/pull/56

Adds instructions on where to go to configure the roles from the 'Configure Security' page
https://github.com/jenkinsci/folder-auth-plugin/pull/55

Created the dark theme:
https://github.com/jenkinsci/dark-theme/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Atimja
https://github.com/jenkinsci/jenkins/pull/4752

Reported dark theme issues for others to contribute:
https://github.com/jenkinsci/dark-theme/issues?q=is%3Aissue+sort%3Aupdated-desc+author%3Atimja

Reported a number of issues in the folder-auth plugin:
https://issues.jenkins-ci.org/browse/JENKINS-62443?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20folder-auth-plugin%20AND%20reporter%20%20%3D%20timja%20

And I've also reviewed a number of issues and PRs:
https://github.com/issues?q=is%3Aissue+is%3Aopen+archived%3Afalse+commenter%3Atimja+sort%3Aupdated-desc+user%3Ajenkinsci

https://github.com/pulls?q=is%3Apr+is%3Aopen+archived%3Afalse+commenter%3Atimja+sort%3Aupdated-desc+user%3Ajenkinsci

I've also tweeted about the dark theme here:
https://twitter.com/Tjaynz/status/1266018525518364675

## Screenshots

Linked on the pull requests

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @timja for code and documentation,
