### ISSUE TITLE
Formatted README.md to suit conventions

### ISSUE THREAD

**Issue by nimishbongale** [jenkinsci/ui-ux-hackfest-2020#153]
Reformatted the README.md according to standard github best practices for the calendar-view-plugin.

## Links 

* https://github.com/jenkinsci/calendar-view-plugin/pull/23

## Screenshots

![jenkins2](https://user-images.githubusercontent.com/43414361/83162127-f33e5880-a126-11ea-8e78-03a074ef688e.PNG)

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @nimishbongale for documentation

**Comment by oleg-nenashev** [comment]
Thanks!
