### ISSUE TITLE
Updated Wording around LTS to Weekly Migration

### ISSUE THREAD

**Issue by sethmccombs** [jenkinsci/ui-ux-hackfest-2020#161]
**Summary:** 
The wording around switching to a weekly build from LTS was a little confusing, a small tweak to make it more readable.

## Links 

https://www.jenkins.io/download/lts/#switching-from-lts-to-weekly
https://github.com/jenkins-infra/jenkins.io/pull/3375

## Screenshots
N/A

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @sethmccombs  for documentation
