### ISSUE TITLE
Reviewed Documentation-as-code changes

### ISSUE THREAD

**Issue by nlk35** [jenkinsci/ui-ux-hackfest-2020#165]
Reviewed Documentation-as-code changes for fstrigger-plugin document migration

## Links 

https://github.com/jenkinsci/fstrigger-plugin/pull/8#pullrequestreview-420441236

**Comment by oleg-nenashev** [comment]
Thanks!

@all-contributors please add @nik35 for reviews

**Comment by oleg-nenashev** [comment]
@all-contributors please add @nlk35  for reviews
