### ISSUE TITLE
UI/UX testing of dark-theme. Empty jenkins instance, no plugins

### ISSUE THREAD

**Issue by EstherAF** [jenkinsci/ui-ux-hackfest-2020#166]
Summary: Testing of the Dark-theme in an empty jenkins instance, without plugins.

## Links 

Issues created:
* https://github.com/jenkinsci/dark-theme/issues/36
* https://github.com/jenkinsci/dark-theme/issues/35
* https://github.com/jenkinsci/dark-theme/issues/34
* https://github.com/jenkinsci/dark-theme/issues/33
* https://github.com/jenkinsci/dark-theme/issues/32
* https://github.com/jenkinsci/dark-theme/issues/31

## Screenshots

The screenshots are in the issues linked before

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @EstherAF  for testing
