### ISSUE TITLE
Migrated translation plugin to Documentation-as-code

### ISSUE THREAD

**Issue by nlk35** [jenkinsci/ui-ux-hackfest-2020#172]
I have migrated all docs to Github.

## Links 

https://github.com/jenkinsci/translation-plugin/pull/21

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! i will need to polish this documentation later a bit to reflect the current state of the plugin, but it is a great foundation work for the migration

@all-contributors please add @nlk35 for documentation
