### ISSUE TITLE
CSS variables API and dark theme contributions

### ISSUE THREAD

**Issue by fqueiruga** [jenkinsci/ui-ux-hackfest-2020#179]
Review CSS variables API and do small adjustments.

## Links 

- https://github.com/timja/jenkins/pulls?q=is%3Apr+author%3Afqueiruga+
- https://github.com/jenkinsci/dark-theme/pulls?q=is%3Apr+author%3Afqueiruga+

## Screenshots

N/A

**Comment by timja** [comment]
@allcontributors please add @fqueiruga for code and reviews
