### ISSUE TITLE
Convert 'Matrix-based security' wiki page to jenkins.io 

### ISSUE THREAD

**Issue by v1v** [jenkinsci/ui-ux-hackfest-2020#184]
Migrate [Matrix-based security](https://wiki.jenkins.io/display/JENKINS/Matrix-based+security)

## Links
- jenkins-infra/jenkins.io#3390
- jenkins-infra/jenkins.io#3391
- jenkins-infra/jenkins-infra#1499

## Screenshots

See the above-mentioned PRs.

**Comment by oleg-nenashev** [comment]
Looks there is some collision with https://github.com/jenkins-infra/jenkins.io/pull/3352 . There was a ticket for this migration already AFAICT

**Comment by v1v** [comment]
My bad, somehow I looked for any references but I was 🙈
