### ISSUE TITLE
Review some PRs related to the migration from the wiki

### ISSUE THREAD

**Issue by v1v** [jenkinsci/ui-ux-hackfest-2020#187]
Provide some feedback in some PRs related to the wiki migration

## Links 

- https://github.com/jenkins-infra/jenkins.io/pull/3384
- https://github.com/jenkins-infra/jenkins.io/pull/3385
- https://github.com/jenkins-infra/jenkins.io/pull/3392

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @v21v for review

**Comment by MarkEWaite** [comment]
@all-contributors please add @v1v for review
