### ISSUE TITLE
Help reviewing and shaping the "Jenkins with Reverse Proxy" documentation page

### ISSUE THREAD

**Issue by dduportal** [jenkinsci/ui-ux-hackfest-2020#189]
Summary: Help reviewing and shaping the "Jenkins with Reverse Proxy" documentation page (to migrate content from different wiki pages).

## Links 

- Issue: https://github.com/jenkins-infra/jenkins.io/issues/3204
- Associated PR: https://github.com/jenkins-infra/jenkins.io/pull/3386

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @dduportal for reviews
