### ISSUE TITLE
Convert 'Authenticating scripted clients' wiki page to jenkins.io

### ISSUE THREAD

**Issue by zaycodes** [jenkinsci/ui-ux-hackfest-2020#190]
Migrate [Authenticating scripted clients](https://wiki.jenkins.io/display/JENKINS//Authenticating+scripted+clients)

### Links
jenkins-infra/jenkins.io#3388
jenkins-infra/jenkins.io#3201
jenkins-infra/jenkins-infra#1503

### Screenshots
See the above-mentioned PRs.

**Comment by oleg-nenashev** [comment]
Thanks for your contributions!

@all-contributors please add @zaycodes for documentation
