### ISSUE TITLE
Create 'Reverse proxy configuration' page(s) on jenkins.io

### ISSUE THREAD

**Issue by zaycodes** [jenkinsci/ui-ux-hackfest-2020#191]
Migrate Authenticating scripted clients

Links
jenkins-infra/jenkins.io#3386
jenkins-infra/jenkins.io#3204 
jenkins-infra/jenkins.io#3218 
jenkins-infra/jenkins.io#3215 
jenkins-infra/jenkins.io#3185 
jenkins-infra/jenkins.io#3223 
jenkins-infra/jenkins.io#2886
jenkins-infra/jenkins-infra#

Screenshots
See the above-mentioned PRs.

**Comment by oleg-nenashev** [comment]
Thank you @zaycodes and @dduportal for working on these documentation sections!
