### ISSUE TITLE
Reworked sourcemap generation

### ISSUE THREAD

**Issue by 95jonpet** [jenkinsci/ui-ux-hackfest-2020#192]
Reworked my previous PR https://github.com/jenkinsci/jenkins/pull/4753 to work with included .less-files.

## Links 

* https://github.com/jenkinsci/jenkins/pull/4753

### Before fix

![](https://user-images.githubusercontent.com/4572231/83195585-bda36a80-a13a-11ea-8518-1d68fa78a90e.png)

![](https://user-images.githubusercontent.com/4572231/83195725-fa6f6180-a13a-11ea-8779-080fbe951da9.png)

### After fix

![](https://user-images.githubusercontent.com/4572231/83303577-919ced80-a1fd-11ea-8438-9318d69ba77b.png)

![](https://user-images.githubusercontent.com/4572231/83303674-c4df7c80-a1fd-11ea-80ec-4df0c3542ffb.png)

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!
