### ISSUE TITLE
Document how to migrate to using buildsDir

### ISSUE THREAD

**Issue by rkivisto** [jenkinsci/ui-ux-hackfest-2020#198]
Summary: If a user has a number of existing build results in their `JENKINS_HOME`, and they want to start using the `jenkins.model.Jenkins.buildsDir` [system property](https://www.jenkins.io/doc/book/managing/system-properties/), I'm adding the documentation to explain how to migrate existing build results.

## Links 

* https://github.com/jenkins-infra/jenkins.io/pull/3387

## Screenshots

![Jenkins_Features_Controlled_with_System_Properties](https://user-images.githubusercontent.com/19917557/83309887-69e75e80-a1d8-11ea-851f-a653ac818c3f.png)

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @rkivisto  for docs
