### ISSUE TITLE
Improve developer documentation

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/ui-ux-hackfest-2020#203]
Summary: A few minor enhancements to developer docs

## Links 

https://github.com/jenkins-infra/jenkins.io/pull/3358
https://github.com/jenkins-infra/jenkins.io/pull/3360
https://github.com/jenkins-infra/jenkins.io/pull/3397

## Screenshots

n/a

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!
