### ISSUE TITLE
Jenkins is the Way - User Story provided

### ISSUE THREAD

**Issue by mtreeman** [jenkinsci/ui-ux-hackfest-2020#207]
Just submitted my user story to https://jenkinsistheway.io and spread the word on twitter. The story is not up yet. Awesome community, looking forward to provide some more help in the future

## Links 

* <https://twitter.com/bau_mark/status/1266623749253730310?s=20>

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! Looking forward to read your story!

@all-contributors please add @mtreeman for content
