### ISSUE TITLE
Migrated ruby-runtime plugin to Documentation as code

### ISSUE THREAD

**Issue by guptaprakhariitr** [jenkinsci/ui-ux-hackfest-2020#208]
Migrated all docs to github
## Links 

https://github.com/jenkinsci/ruby-runtime-plugin/pull/7

## Screenshots

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! I believe this work has started before the hackfest timeframe was over, so I will integrate this issue. Will try to help to get it landed
