### ISSUE TITLE
Migrated python-plugin from Wiki to GitHub

### ISSUE THREAD

**Issue by elliot-smith77** [jenkinsci/ui-ux-hackfest-2020#210]
Summary: Migrated python-plugin from Wiki to GitHub.  Added extra notes, tags and screenshot.  Was not able to add changelog tag though.  

## Links 

* https://github.com/jenkinsci/python-plugin/pull/9

Elliot Smith
elliotsmith775@gmail.com

**Comment by oleg-nenashev** [comment]
Hi @elliot-smith77 , thanks for your contribution! From what I see the pull request was submitted on May 31, after the event was over. Could you please clarify the timeframe of this contribution?

Regardless of the hackfest, your contribution is much appreciated!

**Comment by elliot-smith77** [comment]
Hi @oleg-nenashev , like 90% on May 29th, though was late on final check and pull request.  I thought maybe it was extended through weekend as I could still submit an issue.  

No worries, thanks for the informative videos through the week : ) .

**Comment by oleg-nenashev** [comment]
@elliot-smith77 thanks  for the clarification. I will discuss this case with other admins and circle back later

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @elliot-smith77  for documentation

**Comment by oleg-nenashev** [comment]
@elliot-smith77 Just FYI, we agreed to count it. Thanks again for your contribution, and welcome to the Jenkins community! We will always appreciate your contributions, any time. https://jenkins.io/participate
