### ISSUE TITLE
Made improvements to IntelliJ IDEA plugin for Stapler

### ISSUE THREAD

**Issue by duemir** [jenkinsci/ui-ux-hackfest-2020#211]
Summary: Migrated to Gradle build so that it can be built continuously and started working on migrating to modern features so that plugin works right on the latest IntelliJ IDEA

## Links 

* https://github.com/stapler/idea-stapler-plugin/pull/4
* https://github.com/stapler/idea-stapler-plugin/pull/20
* https://github.com/stapler/idea-stapler-plugin/pull/16
* https://ci.jenkins.io/job/Stapler/job/idea-stapler-plugin/

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! I confirm that a significant part of the referenced pull requests has been done during the hackfest.

@all-contributors please add @duemir  for tools
