### ISSUE TITLE
Built-in theme support for simple-themes-plugin

### ISSUE THREAD

**Issue by timja** [jenkinsci/ui-ux-hackfest-2020#212]
Summary: Added a theme manager and extension point with the dark theme implementing it

## Links 

https://github.com/jenkinsci/simple-theme-plugin/pull/17
https://github.com/jenkinsci/dark-theme/pull/77

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! A bit late for the hackfest, but it is still much appreciated
