### ISSUE TITLE
Migrating Configure Content Security Policy wiki page to jenkins.io etc

### ISSUE THREAD

**Issue by megathaum** [jenkinsci/ui-ux-hackfest-2020#214]
Summary: Various documentation issues / tasks

## Links 

* Migrating Configuration Content Security Policy wiki page: https://github.com/jenkins-infra/jenkins.io/pull/3395
* Fix anchor jump in the Glossary: https://github.com/jenkins-infra/jenkins.io/pull/3399
* Investigate unintended auto-redirection to the Chinese version: https://github.com/jenkins-infra/jenkins.io/issues/3336 and https://github.com/jenkins-infra/charts/pull/230/

## Screenshots

N/A

**Comment by oleg-nenashev** [comment]
@all-contributors please add @megathaum  for testing
