### ISSUE TITLE
Review Windows installer page

### ISSUE THREAD

**Issue by megathaum** [jenkinsci/ui-ux-hackfest-2020#215]
Summary: Reviewed Windows installer page migration from wiki

## Links 

* https://github.com/jenkins-infra/jenkins.io/pull/3383#pullrequestreview-420460245

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! I confirm these reviews have been done within the hackfest timeframe

@all-contributors please add @megathaum  for reviews
