### ISSUE TITLE
UX Testing: Unclear hierarchy in subsection titles with table to div changes

### ISSUE THREAD

**Issue by megathaum** [jenkinsci/ui-ux-hackfest-2020#217]
Summary: In Configure Global Security page `configureSecurity` some subsection titles are rendered smaller than their child subsection titles, which makes it very confusing for the user. See screenshot.

Tested  with `docker run --rm -ti -p 8080:8080 -e ID=3895 jenkins/core-pr-tester`

## Links 

* Jira issue created: https://issues.jenkins-ci.org/browse/JENKINS-62518

## Screenshots

<img width="1310" alt="configure-global-security-compare" src="https://user-images.githubusercontent.com/6340362/83363623-1d984c00-a39b-11ea-8e81-6f82aacdea2d.png">

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! A bit late for the hackfest, but it is still much appreciated
