### ISSUE TITLE
Review 'Monitoring' pull request

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/ui-ux-hackfest-2020#23]
Summary: Review [**Monitoring**](https://github.com/jenkins-infra/jenkins.io/pull/3278) pull request

## Links 

* PR https://github.com/jenkins-infra/jenkins.io/pull/3278
* Issue https://github.com/jenkins-infra/jenkins.io/issues/3210

## Screenshots

![image](https://user-images.githubusercontent.com/156685/82502733-0ca32d00-9ab5-11ea-8185-96f21ad67eb5.png)

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @MarkEWaite for reviews

**Comment by vsilverman** [comment]
After merging [pull request 3278](https://github.com/jenkins-infra/jenkins.io/pull/3278) Monitoring  Jenkins page references the following:
![image](https://user-images.githubusercontent.com/2159948/82586436-6276e400-9b4c-11ea-80de-45b9087561a9.png)
