### ISSUE TITLE
Gavin Mogan started tabs for plugins.jenkins.io

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/ui-ux-hackfest-2020#231]
@halkeye implemented a working prototype of a tabbed interface for the plugins.jenkins.io site.

## Links 

* https://jenkins-plugins.g4v.dev/jira/#releases
* https://jenkins-plugins.g4v.dev/git/#releases
* https://github.com/jenkins-infra/plugin-site/pull/250

### Releases of Configuration as Code plugin (example)

![image](https://user-images.githubusercontent.com/156685/83411782-24908000-a3d6-11ea-8fba-e0f1ccc7fc63.png)

### Releases of Jira plugin (example)

![image](https://user-images.githubusercontent.com/156685/83411055-bd260080-a3d4-11ea-97b6-129d4299625c.png)

**Comment by oleg-nenashev** [comment]
Needs feedback from @halkeye before we act on it

**Comment by halkeye** [comment]
yep will get back to it after work :)

**Comment by halkeye** [comment]
I've given all my feedback i think I can.

**Comment by MarkEWaite** [comment]
@halkeye confirmed to me over Gitter that he worked on the plugins site during the Hackfest.  He had not registered for the Hackfest, but his work was definitely done during the time of the Hackfest and is very much a user experience improvement.

@oleg-nenashev your choice whether to add or not...

**Comment by oleg-nenashev** [comment]
I will add @halkeye to the list, but, to be fair to registered hackfest participants, they will have a priority w.r.t. swag

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @halkeye for code
