### ISSUE TITLE
Convert arrow pngs to CSS

### ISSUE THREAD

**Issue by EstherAF** [jenkinsci/ui-ux-hackfest-2020#232]
Changes in jenkins-core CSS to tackle the [JENKINS-62496 Convert arrow pngs to CSS](https://issues.jenkins-ci.org/browse/JENKINS-62496): 

## Links 

* [JENKINS-62496](https://issues.jenkins-ci.org/browse/JENKINS-62496)
* [PR](https://github.com/jenkinsci/jenkins/pull/4757)

## Screenshots

n/a

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! I confirm that this work started before the end of the hackfest.

@all-contributors please add @EstherAF  for code
