### ISSUE TITLE
Review of the PR #4752 (Add CSS variables - prerequisite for Dark mode)

### ISSUE THREAD

**Issue by EstherAF** [jenkinsci/ui-ux-hackfest-2020#233]
Review of the PR https://github.com/jenkinsci/jenkins/pull/4752 (Add CSS variables - prerequisite for Dark mode)

## Links 

* Link to comment in the PR: https://github.com/jenkinsci/jenkins/pull/4752#discussion_r432409983

**Comment by oleg-nenashev** [comment]
Hi @EstherAF . Sorry, but I was unable to find review comments from tyou in this pull request. Could you please clarify the contribution?

**Comment by EstherAF** [comment]
> Hi @EstherAF . Sorry, but I was unable to find review comments from tyou in this pull request. Could you please clarify the contribution?

It is a long PR, indeed :sweat_smile: https://github.com/jenkinsci/jenkins/pull/4752#discussion_r432409983

**Comment by oleg-nenashev** [comment]
You are right, thanks!

@all-contributors please add @EstherAF  for reviews
