### ISSUE TITLE
Migrate plugin documentation to github

### ISSUE THREAD

**Issue by res0nance** [jenkinsci/ui-ux-hackfest-2020#29]
Move plugin documentation from wiki to github

## Links 

https://github.com/jenkinsci/parameterized-remote-trigger-plugin/pull/72
https://github.com/jenkinsci/basic-branch-build-strategies-plugin/pull/8
https://github.com/jenkinsci/greenballs-plugin/pull/13
https://github.com/jenkinsci/rebuild-plugin/pull/65

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @res0nance for docs
