### ISSUE TITLE
All Contributors - Contribution links do not properly list contributions through issues

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/ui-ux-hackfest-2020#35]
Currently we do not override the default contribution type links, so defaults come from the master config: https://allcontributors.org/docs/en/bot/configuration . These defaults do work well for a single-repo tracing, but not for our multi-org multi-repo tracing. To be replaced by contribution queries

**Comment by bigdevlarry** [comment]
Hi @oleg-nenashev I would love to look into this issue . Mind providing me to relevant links to help me better understand what's meant by contribution queries

**Comment by oleg-nenashev** [comment]
Sorry for missing the comment. It is just a hackfest repo issue which is fairly minor. I suggest to focus on the Jenkins documentation and UX, we can handle the hackfest tooling for the next event

**Comment by oleg-nenashev** [comment]
Will consider it doing for the next event
