### ISSUE TITLE
Enable alphabetical ordering of contributors?

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/ui-ux-hackfest-2020#39]
Right now https://github.com/jenkinsci/ui-ux-hackfest-2020#contributors in an order they were added. Would we like to switch to the alphabetical ordering @jenkinsci/ui-ux-hackfest-2020-orgs ?

**Comment by res0nance** [comment]
I think switching to alphabetical order is fine, but organizations like CDF / Cloudbees should be in a separate section from individuals.
