### ISSUE TITLE
Migrated plugin documentation to github

### ISSUE THREAD

**Issue by res0nance** [jenkinsci/ui-ux-hackfest-2020#41]
Migrated plugin docs from wiki to github

## Links 

https://github.com/jenkinsci/cloudbees-disk-usage-simple-plugin/pull/28
https://github.com/jenkinsci/parameterized-scheduler-plugin/pull/62
https://github.com/jenkinsci/build-user-vars-plugin/pull/18
https://github.com/jenkinsci/pipeline-aws-plugin/pull/231

**Comment by oleg-nenashev** [comment]
Processed all linked PRs, thanks!
