### ISSUE TITLE
Reviewed documentation and UI improvements

### ISSUE THREAD

**Issue by res0nance** [jenkinsci/ui-ux-hackfest-2020#42]
Review incoming doc updates and plugin UI improvements

## Links 

https://github.com/jenkins-infra/jenkins.io/pull/3337
https://github.com/jenkins-infra/jenkins.io/pull/3338
https://github.com/jenkinsci/folder-auth-plugin/pull/55

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @res0nance for reviews
