### ISSUE TITLE
Docker installation guide to use jenkins/jenkins image

### ISSUE THREAD

**Issue by BarakStout** [jenkinsci/ui-ux-hackfest-2020#52]
Summary: PR to rewrite the Docker installation guide to use the jenkins/jenkins image instead of the Blue Ocean images

## Links 

* https://github.com/jenkins-infra/jenkins.io/pull/3346

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! It is a hard topic, and your work on it is much appreciated!

@all-contributors please add @BarakStout for documentation

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! Let's proceed in the pull request
