### ISSUE TITLE
Reviewed issues for Jenkins Documentation

### ISSUE THREAD

**Issue by vsilverman** [jenkinsci/ui-ux-hackfest-2020#53]
Summary: I had reviewed several issues, related to [Jenkins Doc](https://www.jenkins.io).
The snapshot of reviewed issues is shown below

![image](https://user-images.githubusercontent.com/2159948/82827911-d70b9480-9e64-11ea-9664-9442fb55e73a.png)

## Links 

* [Fix videos](https://github.com/jenkins-infra/jenkins.io/issues/3301)
* [Getting started with Docker](https://github.com/jenkins-infra/jenkins.io/issues/3300)
* [How-To Guides](https://github.com/jenkins-infra/jenkins.io/issues/3134)
* [Jenkins and Docker](https://github.com/jenkins-infra/jenkins.io/issues/3098)
* [Fix the Mailing Lists page](https://github.com/jenkins-infra/jenkins.io/issues/3064)

**Comment by oleg-nenashev** [comment]
Thanks @vsilverman !

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @vsilverman  for reviews
