### ISSUE TITLE
Jenkins Is The Way!

### ISSUE THREAD

**Issue by vsilverman** [jenkinsci/ui-ux-hackfest-2020#54]
Summary: My latest Jenkins related posts include the following:

## Links 

* [Jenkins Hackfest on LinkedIn](https://www.linkedin.com/posts/vladsilverman_jenkins-uiux-hackfest-activity-6670716601056272384-eL_O/)

## Screenshots

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

![image](https://user-images.githubusercontent.com/2159948/82830021-7b8fd580-9e69-11ea-8062-ff9b8054e4ac.png)

**Comment by oleg-nenashev** [comment]
I probably need to add a custom icon for spread-the-word . 📢 is currently used for talks

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @vsilverman  for sharing

**Comment by oleg-nenashev** [comment]
@all-contributors please add @vsilverman for  custom

**Comment by oleg-nenashev** [comment]
@all-contributors please add @vsilverman  for content
