### ISSUE TITLE
Migrated fingerprints from wiki

### ISSUE THREAD

**Issue by stellargo** [jenkinsci/ui-ux-hackfest-2020#56]
Summary: Migration of the fingerprints wiki page at https://wiki.jenkins.io/display/JENKINS/Fingerprint to jenkins.io

## Links 

* https://github.com/jenkins-infra/jenkins.io/pull/3351
* https://github.com/jenkins-infra/jenkins.io/issues/2908

**Comment by oleg-nenashev** [comment]
Thank you!
