### ISSUE TITLE
[JENKINS-62332] Show when a newer plugin version exists

### ISSUE THREAD

**Issue by daniel-beck** [jenkinsci/ui-ux-hackfest-2020#57]
## Background

The Jenkins project offers update sites versioned to correspond to recent LTS baselines: https://github.com/jenkins-infra/update-center2/tree/master/site#multiple-update-sites-for-different-version-ranges

As a side effect, there are update site for older Jenkins core releases that offer plugin releases that aren't the latest, since newer releases are incompatible with the installed version of Jenkins. Users are not informed that newer (incompatible) versions exist.

## Solution

Show on the Jenkins UI when the latest offered release is not the latest release that exists, offering an incentive to admins to update Jenkins.

## Links 

* https://github.com/jenkins-infra/update-center2/pull/382
* https://github.com/jenkinsci/jenkins/pull/4742

## Screenshots

See core PR.

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @daniel-beck for code
