### ISSUE TITLE
Un-inline resources to prepare CSP adoption

### ISSUE THREAD

**Issue by Wadeck** [jenkinsci/ui-ux-hackfest-2020#59]
Summary: Un-inline JavaScript and CSS from Jelly views, to have the possibility in the future to include a strict CSP into Jenkins, that will prevent 99% of the XSS.

Normally, most of the PRs do not change the visual elements, just the technical implementation.

## Links 

* https://github.com/jenkinsci/jenkins/pull/4741
* https://github.com/jenkinsci/jenkins/pull/4743

## Screenshots

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @Wadeck for code
