### ISSUE TITLE
[JENKINS-62421] Added aria-labels to username & password input fields

### ISSUE THREAD

**Issue by romenrg** [jenkinsci/ui-ux-hackfest-2020#60]
To improve accessibility, now the username and password input fields in the login page include aria-labels, than can be read by screen readers, for instance. Those labels are also localized, using the same property the placeholders of the inputs were using, to provide translations.

## Links 

* https://github.com/jenkinsci/jenkins/pull/4740

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @romenrg  for code
