### ISSUE TITLE
 Migrated 'Matrix-based security' from wiki to jenkins.io

### ISSUE THREAD

**Issue by megathaum** [jenkinsci/ui-ux-hackfest-2020#66]
Summary: Migrated 'Matrix-based security' page from wiki to jenkins.io

* Replaced "slave" with "agent"
* Removed obsolete note about "dangerous" permission
* Added explanation about the matrix based security so that everything is contained in one place  (in preparation of https://github.com/jenkins-infra/jenkins.io/issues/3348) 

## Links 

* https://github.com/jenkins-infra/jenkins.io/pull/3352

**Comment by timja** [comment]
@allcontributors please add @megathaum for documentation
