### ISSUE TITLE
UX Testing: dockerhub-notification plugin job config breaks with form changes

### ISSUE THREAD

**Issue by fqueiruga** [jenkinsci/ui-ux-hackfest-2020#74]
Testing the drag & drop behaviour for the dockerhub-notification-plugin (https://github.com/jenkinsci/dockerhub-notification-plugin) I have found that its configuration on freestyle jobs does not work correctly.

It redefines several Jenkins Core widgets such as `f:optionalBlock` and `f:expandableTextbox`, and they stop working.

Submitting the form does not save the configuration.

## Links 

N/A

## Screenshots

<details>
<summary>Behaviour on current Jenkins</summary>

<img width="1321" alt="Captura de pantalla 2020-05-26 a las 16 23 00" src="https://user-images.githubusercontent.com/5738588/82912478-76b44a00-9f6d-11ea-9706-b6a1b5a286ed.png">

<img width="1313" alt="Captura de pantalla 2020-05-26 a las 16 23 09" src="https://user-images.githubusercontent.com/5738588/82912544-86339300-9f6d-11ea-8f62-f36961983785.png">

<img width="1289" alt="Captura de pantalla 2020-05-26 a las 16 23 15" src="https://user-images.githubusercontent.com/5738588/82912558-89c71a00-9f6d-11ea-89ea-80963541df7c.png">

</details>

<details>
<summary>Wrong behaviour with new form layout</summary>

<img width="1314" alt="Captura de pantalla 2020-05-26 a las 16 22 25" src="https://user-images.githubusercontent.com/5738588/82912639-9cd9ea00-9f6d-11ea-8b16-cbc8979caba8.png">

<img width="1322" alt="Captura de pantalla 2020-05-26 a las 16 22 37" src="https://user-images.githubusercontent.com/5738588/82912647-a06d7100-9f6d-11ea-9eb9-16bebc14beba.png">

</summary>

**Comment by fqueiruga** [comment]
I have ported this issue to the OSS JIRA tracker https://issues.jenkins-ci.org/browse/JENKINS-62464

**Comment by timja** [comment]
@allcontributors please add @fqueiruga for testing

**Comment by oleg-nenashev** [comment]
@allcontributors please add @fqueiruga for reviews
