### ISSUE TITLE
Indicate the language of the page in the footer

### ISSUE THREAD

**Issue by aytuncbeken** [jenkinsci/ui-ux-hackfest-2020#75]
Summary: Indicate the language of the page in the footer

## Links 

https://issues.jenkins-ci.org/browse/JENKINS-62419

* https://issues.jenkins-ci.org/browse/JENKINS-62419
* https://github.com/jenkinsci/jenkins/pull/4746

## Screenshots

Screenshots are in the Jira Issue.

**Comment by oleg-nenashev** [comment]
Thank you!

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @aytuncbeken  for code
