### ISSUE TITLE
Migrate "Using local language" from wiki to jenkins.io

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/ui-ux-hackfest-2020#79]
Summary: Migrate "Using local language" to jenkins.io

## Links 

* https://github.com/jenkins-infra/jenkins.io/pull/3356

## Screenshots

![jenkins-in-italian](https://user-images.githubusercontent.com/156685/82921845-181fa980-9f36-11ea-924c-6707051de4de.png)

**Comment by oleg-nenashev** [comment]
Thank you!
