### ISSUE TITLE
Improve layout for XL screens in the auto grading plugin

### ISSUE THREAD

**Issue by uhafner** [jenkinsci/ui-ux-hackfest-2020#82]
Improve layout for XL screens

## Links 

* https://github.com/jenkinsci/autograding-plugin/pull/50

### Layout on XL and XXL screens

![Layout on XL and XXL screens](https://user-images.githubusercontent.com/503338/82950961-a0d62e00-9fa6-11ea-87b2-05a6483922e4.png)

### Layout on L and smaller screens

![Layout on L and smaller screens](https://user-images.githubusercontent.com/503338/82951060-c95e2800-9fa6-11ea-8c32-fc19ec4eb1bf.png)

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @uhafner for code

**Comment by oleg-nenashev** [comment]
Looks grade, thanks!
