### ISSUE TITLE
Add PostCSS pre-processor

### ISSUE THREAD

**Issue by 95jonpet** [jenkinsci/ui-ux-hackfest-2020#86]
Summary: Added the PostCSS pre-processor for frontend CSS/LESS files. Included autoprefixer to automatically insert browser vendor prefixes.
## Links 

* https://github.com/jenkinsci/jenkins/pull/4747

## Screenshots

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @95jonpet for code
