### ISSUE TITLE
Migrate 'ProcessTreeKiller' from wiki

### ISSUE THREAD

**Issue by bigdevlarry** [jenkinsci/ui-ux-hackfest-2020#87]
## Description

I migrated the ProcessTreeKiller from Wiki to the Destination on jenkins.io: Using Jenkins -> Long-running agent processes where I created an adoc file to copy the converted Ascii format text

Fixed issue #3321

## Link to PR
https://github.com/jenkins-infra/jenkins.io/pull/3364

## Screenshots

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @LarrySul for docs
