### ISSUE TITLE
Remove timestamp from footer

### ISSUE THREAD

**Issue by 95jonpet** [jenkinsci/ui-ux-hackfest-2020#88]
Summary: Removed the "Page generated" timestamp from the footer.

## Links 

* https://github.com/jenkinsci/jenkins/pull/4748

## Screenshots

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! Let's continue the discussion in the pull request
