### ISSUE TITLE
Convert the slave to master access control to github

### ISSUE THREAD

**Issue by bigdevlarry** [jenkinsci/ui-ux-hackfest-2020#89]
Convert the slave to master access on Wiki to Jenkins

Fix #3321

## Links 

https://github.com/jenkins-infra/jenkins.io/pull/3353

* Link 1

## Screenshots

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! We will process it in the pull request
