### ISSUE TITLE
Presented docs migration webinar

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/ui-ux-hackfest-2020#90]
Presented the Docs migration webinar to show people how to migrate documentation from the Jenkins wiki to the jenkins.io site.

## Links 

* [Video](https://youtu.be/KB-NPlRvLoY?list=PLN7ajX_VdyaNll_Aw3M-NIQ042BV5teP9)
* [Slides](https://docs.google.com/presentation/d/1fiVoDFrSNTOHsHT4cIqyOIBKYXG0q5zVn_XPue_Khkw/edit#slide=id.g8061b508ca_0_149)

## Screenshots

![image](https://user-images.githubusercontent.com/156685/82959980-5b9a0800-9f76-11ea-82b0-119c6693e39a.png)

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! I will add it to the repo later today

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!
