### ISSUE TITLE
UX Testing: Help button breaks for some plugins with table to div changes

### ISSUE THREAD

**Issue by megathaum** [jenkinsci/ui-ux-hackfest-2020#91]
Summary: Some help buttons when clicked jumps to the top or the bottom of the page.

Tested `docker run --rm -ti -p 8080:8080 -e ID=3895 jenkins/core-pr-tester`

* Folders plugin (see screenshot and screen recordings attached)
* Jenkins Health Advisor plugin (see screenshot)
...

In the PR test version, when you click on the help button, the navigation jumps to the top of the page, without showing the help text. This behavior does not occur in a previous version.

A similar "jumpy" behavior was observed with the Bitbucket Branch Source plugin *in both the previous and the PR test version*. When you select the checkbox, it jumps to the bottom of the page. This does not happen when you unselect the checkbox (see screen recording [bitbucket.mov.zip](https://github.com/jenkinsci/ui-ux-hackfest-2020/files/4685564/bitbucket.mov.zip)).

## Links 

N/A

## Screenshots
<details>
<summary>Folders plugin - Health metrics in Configure System</summary>

See also screen recordings in [folder-health-metric.zip](https://github.com/jenkinsci/ui-ux-hackfest-2020/files/4685494/folder-health-metric.zip)

<img width="833" alt="folder-health-metric" src="https://user-images.githubusercontent.com/6340362/82959706-ad638200-9fb8-11ea-825c-422b3449e433.png">
</details>

<details>
<summary>Health Advisor Plugin</summary>

<img width="833" alt="health-advisor" src="https://user-images.githubusercontent.com/6340362/82959709-ae94af00-9fb8-11ea-9bf3-3294c4e328d8.png">
</details>

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @megathaum for testing

**Comment by oleg-nenashev** [comment]
Still need to republish it in Jira

**Comment by oleg-nenashev** [comment]
@megathaum Hi. Would it be possible to also post this defect in Jenkins Jira?

**Comment by megathaum** [comment]
@oleg-nenashev I have reported this issue in the OSS JIRA tracker https://issues.jenkins-ci.org/browse/JENKINS-62500

**Comment by oleg-nenashev** [comment]
Thanks a lot!
