### ISSUE TITLE
Added build status definitions to the Glossary etc

### ISSUE THREAD

**Issue by megathaum** [jenkinsci/ui-ux-hackfest-2020#92]
Summary: Various documentation migration from wiki to jenkins.io tasks

## Links 

* Add build status definitions to the Glossary: https://github.com/jenkins-infra/jenkins.io/pull/3368
* Add link to Toulouse JAM MeetUp to the Artwork page: https://github.com/jenkins-infra/jenkins.io/pull/3362
* Terminology update in Glossary (Job <-> Project) https://github.com/jenkins-infra/jenkins.io/pull/3359 

## Screenshots

N/A

**Comment by oleg-nenashev** [comment]
Thanks for your contribution! Let's continue in the pull requests
