### ISSUE TITLE
Reporting this week issues

### ISSUE THREAD

**Issue by vsilverman** [jenkinsci/ui-ux-hackfest-2020#94]
Summary: This report provides a brief summary of the issues, open and closed PRs I had authored or worked on during first couple days of [Jenkins Hackfest](https://www.jenkins.io/events/online-hackfest/2020-uiux/)

## Links 

* [Latest report](https://github.com/jenkins-infra/jenkins.io/issues?q=author%3Avsilverman+sort%3Acreated-desc)

## Screenshots
![image](https://user-images.githubusercontent.com/2159948/82962984-90a65a80-9f76-11ea-887b-57d06536d57b.png)

Please add screenshots if relevant.
If they are already linked from the pull request, no need to duplicate

**Comment by oleg-nenashev** [comment]
Thanks for your contribution!

@all-contributors please add @vsilverman  for docs
